### ISSUE TITLE
Possible bug [1.15.2-1.1]

### ISSUE THREAD

**Issue by Laveticus** [JPANv2/EMCBaubles#1]
I have been experiencing a bug where both the collector necklaces and power flower charms produce zero emc in a particular dimension if I logged out of the world with one of them active on a dark matter pedestal. Can be fixed by turning off the pedestals then exiting and re-loading the world.

Playing with this added to the FTB omnia pack [1.7.0]

**Comment by JPANv2** [comment]
It was a bug where the pedestal placement capacity was being attatched to all worlds, instead of just overworld. The intention was always to have the pedestal only work on the overworld. With a few changes and further testing, this should make it work as intended.
