### ISSUE TITLE
EMC converting belt blacklist doesn't seem to be applied.

### ISSUE THREAD

**Issue by Xnosis** [JPANv2/EMCBaubles#4]
Hey! Awesome mod thanks for your work!

I wanted to blacklist enchanted books from being picked up by the EMC Converting Belt. I added the resource location name for enchanted books to the 'true_blacklist' in configs, but all enchanted books are still being picked up (even the default 'enchanted book' that has no actual enchants). The transmutation table and tablet are both being respected and not picked up by the blacklist. Tested with iron ingots as well and those were still picked up.

PS: GUI to modify blacklist/whitelist in game would be great as well as a keybind to toggle conversion on/off.

> EMC Baubles: 1.0.0
>Projecte: PE1.0.1B
>Forge: 36.0.54
>Minecraft: 1.16.5

### emcbaubles-server.toml
```

["Build Wand Settings"]
	#If you don't need to have the start block and the end block to be the same before actually replacing/filling the blocks. Default false.
	only_one_select = false
	#If this option is selected, together with not requiring same start/end blocks, the block that will be copied will be the last one selected. Default false, meaning the copied block will be the starting one.
	select_end = false
	#Add here the resource location name (ie: "minecraft:dirt") of the blocks that will not be allowed as start block. (Note: These blocks will still be replaced with the replace feature. If you need to block that from happening, use the "Non-replaceable block list").
	start_blacklist = ["minecraft:chest"]
	#Add here the resource location name (ie: "minecraft:dirt") of the blocks that will not be replaced by the replace function. (Note: Blocks defined here will not be considered invalid for copying. For that use "Block selection Blacklist").
	replace_blacklist = ["minecraft:chest"]

["Belt Settings"]
	#If the belt will try to place the item in the inventory if you already have a compatible stack in there.
	fill_first = true
	#If the belt will try to place the item in the inventory if it's a tool.
	ignore_tools = true
	#Add here the resource location name (ie: "minecraft:dirt") of the items that will not be destroyed into EMC by the belt, if the inventory is not full.
	blacklist = ["projecte:transmutation_table"]
	#Add here the resource location name (ie: "minecraft:dirt") of the items that will not be destroyed into EMC by the belt, ever, even if it means not picking them up.
	true_blacklist = ["projecte:transmutation_tablet","minecraft:enchanted_book","minecraft:iron_ingot"]

```

**Comment by JPANv2** [comment]
I tested using these same configs, and everything seemed fine (both the iron ore and the 3 different books I tossed were not deleted). This bug may be caused by a conflict with some other mod that picks up items. If the problem persists with this new release, try sending a mod list to see if there's any conflicts.
