### ISSUE TITLE
Does the 1.12.2 version have the configs folder

### ISSUE THREAD

**Issue by BreazyLantern** [JPANv2/EMCBaubles#5]
I can't find the configs for the 1.12.2 version of the mod. I running it with the most recent forge and only have this mod with projecte and jei running on the mod list.

**Comment by BreazyLantern** [comment]
Oh and I know your not planning on updating the 1.12.2 vers Im just asking if this had the config.

**Comment by JPANv2** [comment]
The 1.12 version has no configs, as it was made at the time for my own personal use, and I just changed parameters on the code.
